### ISSUE TITLE
GT2 belt issue on Y axis

### ISSUE THREAD

**Issue by drepou** [lautr3k/RepRap-iTopie#13]
bonjour Skarab j'ai noté un souci avec la position des trous pour la pièce plastique qui tiens la couroie sur le plateau Y. le souci est que les trous sont pile au milieu de la pièce du coup au montage la courroie frotte contre la pièce plastique. Je pense qu'il faudrai légèrement décaler les trous vers la droite ou la gauche du plateau pour que la pièce plastique soit dans la continuité de l'un des deux cotés de la couroie pour que l'autre coté ne frote pas sur la pièce plastique.

voila voila cf photo sur mon build de la itopie.

**Comment by drepou** [comment]
![img_0842](https://cloud.githubusercontent.com/assets/15879331/11196909/4866a9ec-8cba-11e5-8b46-c83a5781b4d5.JPG)
![img_0843](https://cloud.githubusercontent.com/assets/15879331/11196908/4866300c-8cba-11e5-946d-fe68c56f18d6.JPG)

**Comment by ghost** [comment]
C'étais le cas dans la version Sketchup ! encore un oublie de ma part... 
C'est corriger : 7aff54594a7066a1db0d75d2751005401d440e2c
Merci.
