### ISSUE TITLE
Getting vectorial imagem

### ISSUE THREAD

**Issue by masterviana** [lautr3k/RepRap-iTopie#15]
Hey,

Sorry for the dump question, I'm not know anything about this 3d modeling. 

I want to send the schematic of this model to be cut in a shop with laser, the guy at the shop have asking me about the vectorial image of the scheme, to be able to get exact measures. 

How can I get the vectorial image? 

Thanks

**Comment by ghost** [comment]
This is not an issus, please read the docs : http://reprap.org/wiki/ITopie_Build_Manual export your DXF and find a tools to convert to SVG (vectorial image). If you have more questions please use the formu : http://forums.reprap.org/read.php?151,443928. Thank you.
