### ISSUE TITLE
leadscrew

### ISSUE THREAD

**Issue by pOmelchenko** [lautr3k/RepRap-iTopie#2]
Hi! Watch your work in the neighboring repository already asked a question about the extruder.

Question about X ends. Do you plan in the future to replace the building studs 5mm on leadscew?

I tried to edit the existing model, but due to lack of experience and poor performance sketchup under Linux (Wine) I have nothing good happened.

we are talking about, such screws: http://www.ebay.com/itm/8mm-4-Start-L100-600mm-SS-Lead-Screw-Flange-Nut-For-CNC-3D-Printer-Z-Axis-/131363072975?pt=LH_DefaultDomain_0&var=&hash=item1e95d96bcf

**Comment by ghost** [comment]
Hi, not in the near future, but the x-end hare i3 compatible, you can take any.
http://www.thingiverse.com/thing:293634
http://www.thingiverse.com/thing:289720
http://www.thingiverse.com/thing:362019
