### ISSUE TITLE
broken links in readmes

### ISSUE THREAD

**Issue by greysAcademicCode** [lautr3k/RepRap-iTopie#4]
Hi. Really great project, thanks for publishing your work here!
I plan to build one of these for my research so I might ask a few questions here from time to time.

Some of the links in the README.md files are broken.

**Comment by greysAcademicCode** [comment]
this is fixed.

**Comment by greysAcademicCode** [comment]
Actually, I take it back; the image links are intermittently broken, so I doubt the URLs are wrong.

**Comment by ghost** [comment]
Hi @greysAcademicCode, 

The host has some temporary issue.

Thank you for your interest in this project.
