### ISSUE TITLE
middle feet too short

### ISSUE THREAD

**Issue by greysAcademicCode** [lautr3k/RepRap-iTopie#5]
Hi, It seems that the feet that come down off of the `vertical_plate` are too short and don't touch the ground.
They're exactly `sheet_thickness` too short.

**Comment by greysAcademicCode** [comment]
This PR should fix it: https://github.com/lautr3k/RepRap-iTopie/pull/6

**Comment by ghost** [comment]
Merged, Thank you @greysAcademicCode !

**Comment by greysAcademicCode** [comment]
Thank YOU for a totally sweet design!
