### ISSUE TITLE
2D "feathers" on y motor mount

### ISSUE THREAD

**Issue by greysAcademicCode** [lautr3k/RepRap-iTopie#7]
In the openSCAD 3D rendering, I've noticed some two dimensional "feathers" sticking up from the rounded edges of the y motor mount on the horizontal plate:
![screenshot from 2015-10-11 13-50-24](https://cloud.githubusercontent.com/assets/7349875/10416839/0e7ad2ba-701f-11e5-820a-b36ff66461b1.png)
These feathers are present on stl exports of the plates too, which is really annoying and has already cause me some problems and made me wonder what else might be wrong with the outputs.

The issue here is that openSCAD approximates arcs and so two arcs that should be identical don't always subtract cleanly. PR to workaround this specific spot forthcoming...

**Comment by greysAcademicCode** [comment]
By the way, you can play with $fn in the config file and get them to disappear, but that's not a real solution...

**Comment by greysAcademicCode** [comment]
Here is my PR to fix this: https://github.com/lautr3k/RepRap-iTopie/pull/8

**Comment by ghost** [comment]
Tanks you again! fixed 637fde40f6674c5d42812d071ba63800d3fbc7c8.
